---
master:
  hosts:
    kube: 
      ansible_host: 10.122.122.2

agents:
  hosts:
    kubepi1: 
      ansible_host: 10.122.122.3
    kuberock: 
      ansible_host: 10.122.122.4
    kubepi2: 
      ansible_host: 10.122.122.5
    kubetop: 
      ansible_host: 10.122.122.6
    freshpi: 
      ansible_host: 10.122.122.7

cluster:
  hosts:
    kube:
    kubepi1:
    kuberock:
    kubepi2:
    kubetop:
    freshpi:

raspberry_pi:
  hosts:
    kubepi1:
    kubepi2:
    freshpi:

coldstart:
  hosts:
