- name: Install required software
  hosts: cluster
  become: true
  tasks:

    - name: Install packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - ca-certificates
          - curl
          - nfs-common
        
    - name: Install key
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /mnt/volumes
        state: directory
        mode: '0755'

    - name: Mount the volumes share
      ansible.posix.mount:
        path: /mnt/volumes
        state: mounted
        src: "{{ nfs_host }}:/mnt/user/kubernetes/volumes"
        opts: rw,sync,hard
        fstype: nfs
    

- name: Install docker swarm master
  hosts: master
  become: true
  tasks:
    - name: Leave existing swarm
      shell: docker swarm leave --force
      ignore_errors: true

    - name: Run node initialize
      shell: "docker swarm init --advertise-addr {{ ansible_host }}"
      register: init_return

    - set_fact:
        swarm_join_cmd: "{{ init_return.stdout_lines[4] }}"

    - name: Setup ingress network
      shell: yes | docker network rm ingress -f
    - command: "docker network create \
                --driver overlay \
                --ingress \
                --subnet=10.11.0.0/16 \
                --gateway=10.11.0.2 \
                ingress"

- name: Join workers
  hosts: agents
  become: true
  tasks:
    - name: Leave existing swarm
      shell: docker swarm leave
      ignore_errors: true

    - name: Join swarm
      command: "{{ hostvars['kube']['swarm_join_cmd'] }}"