- name: Configure raspberry pis
  hosts: raspberry_pi
  become: true
  roles:
    - role: prereq
    - role: raspberrypi
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - git
          - python3
          - python3-pip
          - python3-tzlocal
          - python3-sdnotify
          - python3-colorama
          - python3-unidecode
          - python3-apt
          - python3-paho-mqtt
          - python3-requests

    - name: Disable swap
      shell: "dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove && apt purge dphys-swapfile -y && sysctl -w vm.swappiness=0"
      ignore_errors: true

    - name: Git checkout RPi reporter
      ansible.builtin.git:
        repo: https://github.com/ironsheep/RPi-Reporter-MQTT2HA-Daemon.git
        dest: /opt/RPi-Reporter-MQTT2HA-Daemon
        version: v1.8.5

    - name: Install Rpi reporter
      shell: "cd /opt/RPi-Reporter-MQTT2HA-Daemon && pip3 install -r requirements.txt --break-system-packages"

    - name: Create config if required
      stat:
        path: /opt/RPi-Reporter-MQTT2HA-Daemon/config.ini
      register: stat_result

    - name: Copy config
      when: not stat_result.stat.exists
      command: cp /opt/RPi-Reporter-MQTT2HA-Daemon/config.ini.dist /opt/RPi-Reporter-MQTT2HA-Daemon/config.ini

    - name: Modify hostname
      ansible.builtin.lineinfile:
        path: /opt/RPi-Reporter-MQTT2HA-Daemon/config.ini
        regexp: ^#hostname = .*
        line: "hostname = {{ mqtt_host }}"

    - name: Modify username
      ansible.builtin.lineinfile:
        path: /opt/RPi-Reporter-MQTT2HA-Daemon/config.ini
        regexp: ^#username = .*
        line: "username = {{ mqtt_user }}"

    - name: Modify config
      ansible.builtin.lineinfile:
        path: /opt/RPi-Reporter-MQTT2HA-Daemon/config.ini
        regexp: ^#password = .*
        line: "password = {{ mqtt_pass }}"

    - name: Add user to video group
      ansible.builtin.user:
        name: daemon
        groups: 
          - daemon
          - video

    - name: Symlink service file
      ansible.builtin.file:
        src: /opt/RPi-Reporter-MQTT2HA-Daemon/isp-rpi-reporter.service
        dest: /etc/systemd/system/isp-rpi-reporter.service
        state: link

    - name: Enable the service
      ansible.builtin.service:
        name: isp-rpi-reporter
        state: restarted
        enabled: true
