---
- name: Install packages
  hosts: cluster
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - nfs-common
          - vlan
          - net-tools
          - curl
          - iptables
          - docker
          - bridge-utils

- name: Configure Interfaces
  import_playbook: configure_interfaces.yml

- name: Configure Raspberry Pis
  import_playbook: configure_raspberry_pis.yml

- name: Configure Master
  import_playbook: configure_master.yml

- name: Configure Agents
  import_playbook: configure_agents.yml

- name: Configure Deployments
  import_playbook: configure_deployments.yml

