- name: Configure master
  hosts: cluster
  become: true
  tasks:
    - name: Get interface name from provided IP
      set_fact:
        interface_name: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', ansible_host) | map(attribute='device') | first }}"
  
    - name: Setup interfaces
      include_role:
        name: common/setup_vlan
      loop: "{{ vlan_ids }}"

    - name: Add table
      ansible.builtin.lineinfile:
        create: true
        path: "/etc/iproute2/rt_tables.d/vlan{{ item }}.conf"
        line: "{{ item }} vlan{{ item }}"
      loop: "{{ vlan_ids }}"

    - name: Setup routes
      command: "ip rule add prio 0 from {{ vlans[item].vlan_subnet }} table vlan{{ item }}"
      loop: "{{ vlan_ids }}"
    - name: Setup routes
      command: "ip route add {{ vlans[item].vlan_subnet }} dev {{ interface_name }}.{{ item }} table vlan{{ item }}"
      loop: "{{ vlan_ids }}"
    - name: Setup routes
      command: "ip route add default via {{ vlans[item].vlan_gateway }} table vlan{{ item }}"
      loop: "{{ vlan_ids }}"

    - name: Enable IPv4 Forwarding
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.ip_forward = 1
    - command: sysctl -w net.ipv4.ip_forward=1
    
    