- name: Uninstall agents
  hosts: agents
  become: true
  tasks: 
    - name: Kill all
      command: /usr/local/bin/k3s-killall.sh
      ignore_errors: true

    - name: Uninstall agent
      command: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: true

- name: Uninstall master
  hosts: master
  become: true
  tasks:
    - name: Kill all
      command: /usr/local/bin/k3s-killall.sh
      ignore_errors: true

    - name: Uninstall master
      command: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: true

    - name: Remove old configs
      ansible.builtin.file:
        path: /etc/rancher/k3s/
        state: absent