
- name: Determine arch
  ansible.builtin.set_fact:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm' if ansible_architecture == 'aarch64' else 'error' }}"

- name: Download cni plugins
  ansible.builtin.get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v1.5.0/cni-plugins-linux-{{ arch }}-v1.5.0.tgz"
    dest: /tmp/

- name: Extract cni plugin
  ansible.builtin.unarchive:
    src: "/tmp/cni-plugins-linux-{{ arch }}-v1.5.0.tgz"
    dest: /opt/cni/bin/
    remote_src: yes
