- name: Reboot hosts
  hosts: cluster
  gather_facts: true
  tasks: 
    - name: Copy cni plugins
      include_role:
        name: kubernetes/download_cni_plugins

    - debug:
        msg: "{{ ansible_architecture }}"

    - debug:
        msg: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else 'error' }}"