---
ansible_user: "{{ master_user }}"
ansinble_ssh_user: "{{ master_user }}"
ansible_ssh_pass: "{{ master_pw }}"
ansible_become_pass: "{{ master_pw }}"

nfs_host: 10.0.0.2
mariadb_host: 10.10.10.102
mqtt_host: 10.10.10.105
default_gateway: 10.122.122.1
netmask: 255.255.255.0
default_dns1: 9.9.9.9
default_dns2: 8.8.8.8

kubernetes_config_repo: "/mnt/kubernetes/Kubernetes-Configs"

vlans:
  3:
    vlan_name: iotlan
    vlan_subnet: 192.168.3.0/24
    vlan_gateway: 192.168.3.1
  4:
    vlan_name: servlan
    vlan_subnet: 10.10.10.0/24
    vlan_gateway: 10.10.10.1
  6:
    vlan_name: expservlan
    vlan_subnet: 10.101.101.0/24
    vlan_gateway: 10.101.101.1
  7:
    vlan_name: tslan
    vlan_subnet: 10.132.132.0/24
    vlan_gateway: 10.132.132.1

main_interface_name: kubelan

assign_ip: false

deployments:
  - name: pihole
    type: yaml
    command: "kubectl apply -f {{ kubernetes_config_repo }}/pihole"
    dir: "{{ kubernetes_config_repo }}/pihole"
  - name: dashy
    type: yaml
    command: "kubectl apply -f {{ kubernetes_config_repo }}/dashy"
    dir: "{{ kubernetes_config_repo }}/dashy"
  - name: duckdns
    type: yaml
    command: "kubectl apply -f {{ kubernetes_config_repo }}/duckdns"
    dir: "{{ kubernetes_config_repo }}/duckdns"
  - name: gitea
    type: yaml
    command: "kubectl apply -f {{ kubernetes_config_repo }}/gitea"
    dir: "{{ kubernetes_config_repo }}/gitea"
  - name: home_assistant
    type: yaml
    command: "kubectl apply -f {{ kubernetes_config_repo }}/home_assistant"
    dir: "{{ kubernetes_config_repo }}/home_assistant"
  - name: prometheus
    type: cmd
    command: "sh {{ kubernetes_config_repo }}/prometheus/deploy.sh"
  - name: portainer
    type: cmd
    command: "sh {{ kubernetes_config_repo }}/portainer/deploy.sh"